In [2]:
import pandas as pd
import numpy as np
from tqdm import *
pd.set_option('display.max_rows',None)
import tushare as ts
pro = ts.pro_api('6792f89c67a1f228aaf8aa19e6b0ca381504c16d8d5b7f75d76427a5')

In [1]:
import tushare as ts
pro = ts.pro_api('6792f89c67a1f228aaf8aa19e6b0ca381504c16d8d5b7f75d76427a5')
df = pro.news(src='eastmoney', start_date='2021-04-08 00:00:00', end_date='2021-04-08 23:59:00')

In [212]:
news0408 = pro.cctv_news(date='20210408')
news0408

,date,title,content
0,20210408,习近平对深化东西部协作和定点帮扶工作作出重要指示强调 适应形势任务变化 弘扬脱贫攻坚精神 加...,中共中央总书记、国家主席、中央军委主席习近平近日对深化东西部协作和定点帮扶工作作出重要指示指...
1,20210408,新闻特写：“重启”一年 风雨过后见彩虹,一年前的今天，随着武汉的解封，湖北这个中部大省重新回归正常秩序和生活。去年，面对突如其来的新...
2,20210408,韩正出席全国绿化委员会全体会议,全国绿化委员会全体会议8日在北京召开。中共中央政治局常委、国务院副总理、全国绿化委员会主任韩...
3,20210408,【奋斗百年路 启航新征程·同心奔小康】多彩休闲游 致富小康路,乡村振兴，关键是产业要振兴。三年前，山东省临邑县的前杨村还是个省定贫困村，而今，立足乡村旅游...
4,20210408,新修订《粮食流通管理条例》首次明确粮食安全党政同责,国务院新闻办4月8日举行政策例行吹风会。国家发展改革委、粮食和物资储备局、司法部、财政部等部...
5,20210408,海南放宽市场准入特别措施今天发布,今天（4月8日），国家发展改革委、商务部等部门联合出台了《关于支持海南自由贸易港建设放宽市场...
6,20210408,国家卫生健康委通报最新疫情,国家卫生健康委今天（4月8日）通报，4月7日0—24时，31个省（自治区、直辖市）和新疆生产...
7,20210408,新华社综述：触目真相戳穿美国“人权卫士”谎言,新华社今天（4月8日）发表综述，题目是《触目真相戳穿美国“人权卫士”谎言》。综述指出，日前，...
8,20210408,国内联播快讯,中央1561亿元资金推进脱贫地区产业振兴农业农村部今天（4月8日）发布，今年中央财政衔接推进...
9,20210408,国际货币基金组织总裁呼吁加强多边合作,2021年国际货币基金组织和世行春季会议5日至11日在线举行。国际货币基金组织总裁格奥尔吉耶...
10,20210408,全球新冠肺炎确诊病例超1亿3204万例,根据世界卫生组织的统计数据，全球累计新冠肺炎确诊病例已达到132046206例，累计死亡病例...
11,20210408,俄高官批评美在世界各地发展生物实验室,近日，俄罗斯联邦安全会议秘书帕特鲁舍夫在接受俄罗斯《生意人报》采访时说，有充分的理由相信美...
12,20210408,国际联播快讯,英国北爱接连爆发抗议 局势紧张7日，英国北爱尔兰地区首府贝尔法斯特再度爆发抗议示威活动以及纵...
13,20210408,联合国秘书长呼吁吸取卢旺达大屠杀历史教训,4月7日是“反思1994年针对图西族的卢旺达大屠杀国际日”。联合国秘书长古特雷斯在致辞中呼...

In [269]:
news408 = news0408.groupby('date').sum()
news4082 = news408.reset_index()
news4082

,date,title,content
0,20210408,习近平对深化东西部协作和定点帮扶工作作出重要指示强调 适应形势任务变化 弘扬脱贫攻坚精神 加...,中共中央总书记、国家主席、中央军委主席习近平近日对深化东西部协作和定点帮扶工作作出重要指示指...

In [287]:
pro_dict = {
 '北京': 0,
 '上海': 0,
 '天津': 0,
 '重庆': 0,
 '河北': 0,
 '山西': 0,
 '河南': 0,
 '辽宁': 0,
 '吉林': 0,
 '黑龙江': 0,
 '内蒙古': 0,
 '江苏': 0,
 '山东': 0,
 '安徽': 0,
 '浙江': 0,
 '福建': 0,
 '湖北': 0,
 '湖南': 0,
 '广东': 0,
 '广西': 0,
 '江西': 0,
 '四川': 0,
 '海南': 0,
 '贵州': 0,
 '云南': 0,
 '陕西': 0,
 '甘肃': 0,
 '青海': 0,
 '宁夏': 0,
 '新疆': 0,
 '香港': 0,
 '台湾': 0,
 '澳门': 0,
 '西藏': 0,
 }

In [265]:
import jieba
def count_word(text,worddict,date):
    wordsls=jieba.lcut(text)
    for i in wordsls:
        if i in worddict:
            worddict[i] = worddict[i]+1
    wcls=list(worddict.items())
    return date,wcls

In [311]:
b = []
q = count_word(news4082.content[0],pro_dict,news4082.date[0])
b.append(q)
freq_words = pd.DataFrame(b,columns = ['date','words'])
freq_words

       date                                              words
0  20210408  [(北京, 12), (上海, 16), (天津, 0), (重庆, 0), (河北, 0)...

In [291]:
list1 = list(pro_dict)
def split_list(dict,data):
    list1 = list(dict)
    data[list1] = data['words'].apply(pd.Series)
    for i in list1:
        data[[i*2,i*3]] = data[i].apply(pd.Series)
        del data[i]
        del data[i*2]
        data[i]=data[i*3]
        del data[i*3]
    return data
freq_words1 = split_list(pro_dict,freq_words)
freq_words2 = freq_words1.drop('words',axis=1)
freq_words2

,date,北京,上海,天津,重庆,河北,山西,河南,辽宁,吉林,...,云南,陕西,甘肃,青海,宁夏,新疆,香港,台湾,澳门,西藏
0,20210408,3,4,0,0,0,0,0,0,0,...,0,0,1,0,2,0,0,0,0,0

In [327]:
freq_words3 = np.transpose(freq_words2)
freq_words4 = freq_words3.reset_index()
c = str(freq_words2.date[0])
freq_words4.columns = ['area',c]
freq_words5 = freq_words4[1:]
freq_words5.sort_values(c,inplace=True)
freq_words6 = freq_words5[freq_words5['20210408'] > 0]
freq_words6

<ipython-input-327-49c104d865d8>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  freq_words5.sort_values(c,inplace=True)

   area 20210408
27   甘肃        1
21   江西        1
12   江苏        1
19   广东        1
24   贵州        1
16   福建        2
29   宁夏        2
1    北京        3
13   山东        3
2    上海        4
23   海南        7
17   湖北        8

In [232]:
import re
def get_words(text,key,date):
    pattern = re.compile(r'.*?(.{10}%s)'%key) 
    output = re.findall(pattern,text)
    return key,date,output

In [243]:
keys =['电器']

In [244]:
result1 = []
for i in tqdm(range(13)):
    if i <0:
        continue 
    else:
        for key in keys:
            m = get_words(news0408.content[i],key,news0408.title[i])
            result1.append(m)
find_words = pd.DataFrame(result1,columns = ['key','title','words'])
find_words

100%|██████████| 13/13 [00:00<00:00, 166.59it/s]

   key                                              title words
0   电器  习近平对深化东西部协作和定点帮扶工作作出重要指示强调 适应形势任务变化 弘扬脱贫攻坚精神 加...    []
1   电器                                新闻特写：“重启”一年 风雨过后见彩虹    []
2   电器                                    韩正出席全国绿化委员会全体会议    []
3   电器                     【奋斗百年路 启航新征程·同心奔小康】多彩休闲游 致富小康路    []
4   电器                          新修订《粮食流通管理条例》首次明确粮食安全党政同责    []
5   电器                                   海南放宽市场准入特别措施今天发布    []
6   电器                                      国家卫生健康委通报最新疫情    []
7   电器                             新华社综述：触目真相戳穿美国“人权卫士”谎言    []
8   电器                                             国内联播快讯    []
9   电器                                 国际货币基金组织总裁呼吁加强多边合作    []
10  电器                                全球新冠肺炎确诊病例超1亿3204万例    []
11  电器                                 俄高官批评美在世界各地发展生物实验室    []
12  电器                                             国际联播快讯    []

In [91]:
df2 = df.groupby('date').sum()

In [3]:
data = pro.query('stock_basic', exchange='', list_status='L', fields='ts_code,symbol,name,area,industry,list_date,market,exchange,list_status,is_hs')

In [4]:
data[data.symbol == '000002']

,ts_code,symbol,name,area,industry,market,exchange,list_status,list_date,is_hs
1,000002.SZ,000002,万科A,深圳,全国地产,主板,SZSE,L,19910129,S

In [5]:
data.to_csv('./stock_basic.csv')

In [9]:
name_list = list(data['name'])
name_list
#apply(lambda x:x.split('.'))

['平安银行',
 '万科A',
 '国华网安',
 '世纪星源',
 '深振业A',
 '全新好',
 '神州高铁',
 '中国宝安',
 '美丽生态',
 '深物业A',
 '南玻A',
 '沙河股份',
 '深康佳A',
 '*ST中华A',
 '深粮控股',
 '深华发A',
 '深科技',
 '深天地A',
 '特力A',
 '飞亚达',
 '深圳能源',
 '国药一致',
 '深深房A',
 '富奥股份',
 '大悦城',
 '深桑达A',
 '神州数码',
 '中国天楹',
 '华联控股',
 '深南电A',
 '深大通',
 '中集集团',
 '东旭蓝天',
 '中洲控股',
 '深纺织A',
 '泛海控股',
 '京基智农',
 '德赛电池',
 '深天马A',
 '方大集团',
 '皇庭国际',
 '深赛格',
 '华锦股份',
 '中金岭南',
 '农产品',
 '深圳华强',
 '中兴通讯',
 '北方国际',
 '中国长城',
 '华控赛格',
 '华侨城A',
 '特发信息',
 '海王生物',
 '盐田港',
 '深圳机场',
 '天健集团',
 '广聚能源',
 '中信海直',
 'TCL科技',
 '宜华健康',
 '中成股份',
 '丰原药业',
 '川能动力',
 '华数传媒',
 '中联重科',
 '常山北明',
 '国际实业',
 '申万宏源',
 '东方盛虹',
 '美的集团',
 '潍柴动力',
 '许继电气',
 '冀东水泥',
 '金融街',
 '派林生物',
 '长虹华意',
 '胜利股份',
 '*ST藏格',
 'ST地矿',
 '*ST沈机',
 '英特集团',
 '东旭光电',
 '渤海租赁',
 '民生控股',
 '合肥百货',
 '通程控股',
 '吉林化纤',
 '南京公用',
 'ST宜化',
 '东阿阿胶',
 '徐工机械',
 '兴业矿业',
 '华天酒店',
 '粤高速A',
 '张家界',
 '晨鸣纸业',
 '山东路桥',
 '鄂武商A',
 '绿景控股',
 '国新健康',
 'ST生物',
 '京粮控股',
 '中润资源',
 '珠海港',
 '*ST华塑',
 '新金路',
 '丽珠集团',
 '渝开发',
 '国际医学',
 '荣安地产',
 '四环生物',
 '中兵红箭',
 '长航凤凰',
 '长虹美菱',
 '广州浪奇',
 '岭南控股',
 '红太阳',
 '紫光学大',
 '柳工',
 '广弘控股',
 '冰山冷热',
 '穗恒运A',
 '华金资本',
 '顺钠股份',
 '万泽股份',
 '*ST华映',
 '广宇发展',
 '云南白药',
 '粤电力A',
 '中天金融',
 '佛山照明',
 '皖能电力',
 '中原环保',
 '金浦钛业',
 '金圆股份',
 '航天发展',
 '湖南投资',
 '江铃汽车',
 '创元科技',
 '靖远煤电',
 '安道麦A',
 '泰山石油',
 '神州信息',
 '西部创业',
 '莱茵体育',
 '万向钱潮',
 '我爱我家',
 '烽火电子',
 '陕国投A',
 '*ST大集',
 '渝三峡A',
 '海南海药',
 '海德股份',
 '泸州老窖',
 '苏常柴A',
 '*ST大洲',
 'ST海马',
 '粤宏远A',
 '甘化科工',
 '威孚高科',
 '北部湾港',
 '哈工智能',
 '*ST东电',
 '汇源通信',
 '*ST金洲',
 '贵州轮胎',
 '启迪药业',
 '太阳能',
 '平潭发展',
 '大通燃气',
 '*ST宝实',
 '古井贡酒',
 '东北制药',
 '兴蓉环境',
 '青岛双星',
 '建投能源',
 '韶能股份',
 '盛达资源',
 '渤海股份',
 '顺利办',
 '华媒控股',
 '阳光股份',
 '中迪投资',
 '西安旅游',
 'ST天首',
 '焦作万方',
 '大东海A',
 '奥园美谷',
 '海航投资',
 '中油资本',
 '海螺型材',
 '新华联',
 '恒立实业',
 '吉林敖东',
 '长安汽车',
 '远大控股',
 '天茂集团',
 '高新发展',
 '攀钢钒钛',
 '铜陵有色',
 '顺发恒业',
 '三木集团',
 '合金投资',
 '英力特',
 '风华高科',
 '茂化实华',
 '万方发展',
 '西王食品',
 '仁和药业',
 '格力电器',
 '泰达股份',
 '金岭矿业',
 '金科股份',
 '中钨高新',
 '珠海中富',
 '长春高新',
 '天夏退',
 '*ST永林',
 '湖北广电',
 '经纬纺机',
 '美好置业',
 '荣丰控股',
 '*ST金鸿',
 '阳光城',
 '上峰水泥',
 '*ST当代',
 '智度股份',
 '恒天海龙',
 '襄阳轴承',
 '*ST友谊',
 '山推股份',
 '视觉中国',
 '东方电子',
 '远兴能源',
 '中山公用',
 '东北证券',
 '*ST华讯',
 '国城矿业',
 '宝新能源',
 '亚太实业',
 '惠天热电',
 '滨海能源',
 '炼石航空',
 '沈阳化工',
 '模塑科技',
 '厦门信达',
 '正虹科技',
 '恒逸石化',
 '浙江震元',
 'ST双环',
 '中信特钢',
 '河钢股份',
 '贝瑞基因',
 '京蓝科技',
 '锦龙股份',
 '丰乐种业',
 '中兴商业',
 '黑芝麻',
 '韶钢松山',
 '苏宁环球',
 '中原传媒',
 '新能泰山',
 '西安饮食',
 '湖南发展',
 '美锦能源',
 '京东方A',
 '鲁泰A',
 '华东科技',
 '国元证券',
 '燕京啤酒',
 '四川美丰',
 '泰禾集团',
 '振华科技',
 '罗牛山',
 '中交地产',
 'ST南风',
 '航发控制',
 '普洛药业',
 '国海证券',
 '锌业股份',
 '*ST西发',
 '漳州发展',
 '山西路桥',
 '新华制药',
 '浩物股份',
 '中色股份',
 '中百集团',
 '本钢板材',
 '西藏矿业',
 '通化金马',
 '晋控电力',
 '中航西飞',
 '广发证券',
 '中核科技',
 '新兴铸管',
 '甘咨询',
 '*ST平能',
 '美达股份',
 '长江证券',
 '居然之家',
 '北新建材',
 '北大医药',
 '万年青',
 '华神科技',
 '甘肃电投',
 '华闻集团',
 '英洛华',
 '凯撒旅业',
 '中国武夷',
 '中水渔业',
 '酒鬼酒',
 '一汽解放',
 '四川九洲',
 '北京文化',
 '北清环能',
 '*ST银河',
 '云铝股份',
 '铁岭新城',
 '创维数字',
 '冰轮环境',
 '陕西金叶',
 '德展健康',
 '美利云',
 '智慧农业',
 '航锦科技',
 '岳阳兴长',
 '*ST节能',
 '京山轻机',
 '山东海化',
 '超声电子',
 '太钢不锈',
 '启迪环境',
 '东莞控股',
 '天音控股',
 '鲁西化工',
 '五矿稀土',
 '粤桂股份',
 '*ST长动',
 '富通信息',
 '*ST秦机',
 '财信发展',
 '中信国安',
 '承德露露',
 '华茂股份',
 '高鸿股份',
 '石化机械',
 '冀东装备',
 '五粮液',
 '国风塑业',
 '顺鑫农业',
 '海印股份',
 '银星能源',
 '三湘印象',
 'ST安凯',
 '张裕A',
 '吉电股份',
 '新希望',
 '天山股份',
 '云南铜业',
 '潍柴重机',
 '中广核技',
 '华联股份',
 '湖北能源',
 '城发环境',
 '海南高速',
 '中鼎股份',
 '峨眉山A',
 '中嘉博创',
 '*ST胜尔',
 '欢瑞世纪',
 '亚钾国际',
 '双汇发展',
 '津滨发展',
 '鞍钢股份',
 '赣能股份',
 '现代投资',
 '航天科技',
 '新洋丰',
 '云内动力',
 '厦门港务',
 '浙商中拓',
 '景峰医药',
 '数源科技',
 '大亚圣象',
 '南宁糖业',
 '泸天化',
 '钱江摩托',
 '山大华特',
 '电广传媒',
 '嘉凯城',
 '金陵药业',
 '南方汇通',
 '海信家电',
 '佳电股份',
 '河钢资源',
 '众合科技',
 '福星股份',
 '中国铁物',
 '中钢国际',
 '兰州黄河',
 '中粮科技',
 '中关村',
 '华菱钢铁',
 '神火股份',
 '四川双马',
 '华西股份',
 '冀中能源',
 '紫光股份',
 '南天信息',
 '新乡化纤',
 '重药控股',
 '中国重汽',
 '广济药业',
 '*ST河化',
 '欣龙控股',
 '中通客车',
 '东方能源',
 '首钢股份',
 '锡业股份',
 '中南建设',
 '东方钽业',
 '华东医药',
 '天保基建',
 '长源电力',
 '盈峰环境',
 '蓝焰控股',
 '安泰科技',
 '中科三环',
 '*ST高升',
 'ST中基',
 '佛塑科技',
 '银泰黄金',
 '华铁股份',
 '浪潮信息',
 '桂林旅游',
 '*ST众泰',
 '*ST银亿',
 '*ST中绒',
 '山西焦煤',
 '大庆华科',
 '越秀金控',
 '华工科技',
 '九芝堂',
 '诚志股份',
 '闽东电力',
 '皇台酒业',
 '中国中期',
 '新大陆',
 '隆平高科',
 '华润三九',
 '宗申动力',
 '招商港口',
 '豫能控股',
 '招商积余',
 '招商公路',
 '招商蛇口',
 '新和成',
 '鸿达兴业',
 '伟星股份',
 '华邦健康',
 'ST德豪',
 '精功科技',
 '华兰生物',
 '大族激光',
 '天奇股份',
 '传化智联',
 '盾安环境',
 '凯恩股份',
 '中航机电',
 '永新股份',
 '协鑫能科',
 '世荣兆业',
 '东信和平',
 '亿帆医药',
 '京新药业',
 'ST中捷',
 '科华生物',
 '海特高新',
 '苏宁易购',
 '航天电器',
 '山东威达',
 '分众传媒',
 '思源电气',
 '七匹狼',
 '达安基因',
 '巨轮智能',
 '苏泊尔',
 '丽江股份',
 '旺能环境',
 '华帝股份',
 '联创电子',
 '保利联合',
 '双鹭药业',
 '黔源电力',
 '南京港',
 '登海种业',
 '华孚时尚',
 '兔宝宝',
 '美年健康',
 '国光电器',
 '国机精工',
 '宝鹰股份',
 '宁波华翔',
 '紫光国微',
 '三花智控',
 '中工国际',
 '*ST同洲',
 '云南能投',
 '德美化工',
 '得润电子',
 '横店东磁',
 '中钢天源',
 '*ST威尔',
 '云南旅游',
 '粤水电',
 '浙江交科',
 '宏润建设',
 '远光软件',
 '华峰化学',
 '东华软件',
 '瑞泰科技',
 '景兴纸业',
 '黑猫股份',
 '獐子岛',
 '长城退',
 '*ST凯瑞',
 '软控股份',
 '国轩高科',
 '沙钢股份',
 '*ST雪莱',
 '*ST大港',
 '太阳纸业',
 '苏州固锝',
 '中材科技',
 '金螳螂',
 '万邦德',
 '孚日股份',
 '海鸥住工',
 '万丰奥威',
 '*ST东洋',
 '新野纺织',
 '鲁阳节能',
 'ST新海',
 '金智科技',
 '江苏国泰',
 '中泰化学',
 '国脉科技',
 '青岛金王',
 '生意宝',
 '南岭民爆',
 '山河智能',
 '浔兴股份',
 '海翔药业',
 '天康生物',
 '广东鸿图',
 'ST冠福',
 '广博股份',
 '恒宝股份',
 '信隆健康',
 '莱宝高科',
 '沃华医药',
 '沧州明珠',
 '兴化股份',
 '三钢闽光',
 '威海广泰',
 '三变科技',
 '*ST天润',
 '罗平锌电',
 '三维通信',
 '中国海诚',
 '东港股份',
 '紫鑫药业',
 '康强电子',
 '韵达股份',
 '*ST科陆',
 '*ST天马',
 '梦网科技',
 '天邦股份',
 '湘潭电化',
 '银轮股份',
 '南极电商',
 '露天煤业',
 '中环股份',
 '沃尔核材',
 '利欧股份',
 '恒星科技',
 '广宇集团',
 '天津普林',
 '东南网架',
 '安纳达',
 '实益达',
 '顺络电子',
 '拓邦股份',
 '东华科技',
 '贤丰控股',
 '宁波银行',
 '宏达高科',
 '中核钛白',
 '荣盛发展',
 '*ST新光',
 '北纬科技',
 '西部材料',
 '通润装备',
 '北斗星通',
 '广电运通',
 '石基信息',
 '报喜鸟',
 '湖南黄金',
 '通富微电',
 '正邦科技',
 '汉钟精机',
 '三特索道',
 '常铝股份',
 '远望谷',
 '悦心健康',
 '海南发展',
 '宁波东力',
 '红宝丽',
 '莱茵生物',
 '东方锆业',
 'ST惠程',
 '智光电气',
 '芭田股份',
 '楚江新材',
 '澳洋健康',
 '创新医疗',
 '游族网络',
 'ST东网',
 '*ST江特',
 '御银股份',
 '延华智能',
 '中航光电',
 '纳思达',
 '粤传媒',
 '云海金属',
 '怡亚通',
 '海得控制',
 '华天科技',
 '全聚德',
 '广百股份',
 '*ST巴士',
 '中光学',
 '成飞集成',
 '劲嘉股份',
 '融捷股份',
 '如意集团',
 '武汉凡谷',
 '二三四五',
 '方正电机',
 '证通电子',
 '嘉应制药',
 '东晶电子',
 'ST云投',
 '九鼎新材',
 '金风科技',
 '海亮股份',
 '大连重工',
 '国统股份',
 '海利得',
 '准油股份',
 '合肥城建',
 '达意隆',
 '*ST飞马',
 '宏达新材',
 '天融信',
 '大为股份',
 '大立科技',
 '诺普信',
 '三全食品',
 '合力泰',
 '拓日新能',
 '*ST恒康',
 '东华能源',
 '福晶科技',
 '鱼跃医疗',
 '三力士',
 '濮耐股份',
 '江南化工',
 '奥特迅',
 '合兴包装',
 '鸿博股份',
 '科大讯飞',
 '奥维通信',
 '启明信息',
 '塔牌集团',
 '民和股份',
 '安妮股份',
 '大华股份',
 '恒邦股份',
 '天威视讯',
 '奥特佳',
 '盛新锂能',
 '歌尔股份',
 '九阳股份',
 '力合科创',
 '滨江集团',
 '蔚蓝锂芯',
 '北化股份',
 '*ST聚力',
 '华东数控',
 '大洋电机',
 '联化科技',
 '步步高',
 '上海莱士',
 '川大智胜',
 '泰和新材',
 '*ST海陆',
 '*ST兆新',
 '利尔化学',
 '*ST升达',
 '拓维信息',
 '恩华药业',
 '大东南',
 '新华都',
 '西仪股份',
 '浙富控股',
 '陕天然气',
 '卫士通',
 '美邦服饰',
 '华明装备',
 '东方雨虹',
 '川润股份',
 '水晶光电',
 '华昌化工',
 '桂林三金',
 '万马股份',
 '友阿股份',
 '神开股份',
 '久其软件',
 '*ST联络',
 '光迅科技',
 '博深股份',
 '天润工业',
 '亚太股份',
 '世联行',
 '保龄宝',
 '奇正藏药',
 '超华科技',
 'ST宇顺',
 'ST禾盛',
 '星期六',
 '奥飞娱乐',
 '罗莱生活',
 '信立泰',
 '精艺股份',
 '辉煌科技',
 '博云新材',
 '中电兴发',
 '圣农发展',
 '太阳电缆',
 '齐心集团',
 '西部建设',
 '美盈森',
 '洋河股份',
 '南国置业',
 'ST云网',
 '北新路桥',
 '威创股份',
 '中利集团',
 '东方园林',
 '海大集团',
 '三泰控股',
 '日海智能',
 '南山控股',
 '焦点科技',
 '亚联发展',
 '众生药业',
 '久立特材',
 '乐通股份',
 '海峡股份',
 '华英农业',
 '理工环科',
 '*ST雅博',
 '普利特',
 '洪涛股份',
 '永太科技',
 '富安娜',
 '新朋股份',
 '皇氏集团',
 '得利斯',
 '皖通科技',
 '仙琚制药',
 'ST罗普',
 '英威腾',
 '科华数据',
 'ST人乐',
 '赛象科技',
 '奥普光电',
 '积成电子',
 '格林美',
 '新纶科技',
 '巨力索具',
 '慈文传媒',
 '海宁皮城',
 '潮宏基',
 '柘中股份',
 '泰尔股份',
 '高乐股份',
 '精华制药',
 '北京科锐',
 '漫步者',
 '顺丰控股',
 '杰瑞股份',
 '*ST天娱',
 '兴民智通',
 '*ST赫美',
 '富临运业',
 '森源电气',
 '同德化工',
 '神剑股份',
 '汉王科技',
 '隆基机械',
 '中恒电气',
 '永安药业',
 '台海核电',
 '康力电梯',
 '太极股份',
 '卓翼科技',
 '亚太药业',
 '北方华创',
 '伟星新材',
 '千方科技',
 '中锐股份',
 '亚厦股份',
 '新北洋',
 '国创高新',
 '章源钨业',
 '宏创控股',
 '科远智慧',
 '双箭股份',
 '蓝帆医疗',
 '合众思壮',
 '东山精密',
 '大北农',
 '天原股份',
 '维信诺',
 '新亚制程',
 '航天彩虹',
 '信邦制药',
 '长青股份',
 '北京利尔',
 '力生制药',
 '联发股份',
 '双象股份',
 '星网锐捷',
 '梦洁股份',
 '垒知集团',
 '海普瑞',
 '省广集团',
 '中远海科',
 '和而泰',
 '爱仕达',
 '嘉欣丝绸',
 '四维图新',
 '远东传动',
 '多氟多',
 '齐翔腾达',
 '雅克科技',
 '广联达',
 '延安必康',
 '汉森制药',
 '雷科防务',
 '高德红外',
 '海康威视',
 '爱施德',
 '深南股份',
 '*ST康盛',
 '天虹股份',
 '毅昌股份',
 '达实智能',
 '科伦药业',
 '中粮资本',
 '贵州百灵',
 '凯撒文化',
 '*ST胜利',
 'ST尤夫',
 '云南锗业',
 '兆驰股份',
 '杭氧股份',
 '棕榈股份',
 '九安医疗',
 '太安堂',
 '万里扬',
 '长江健康',
 '兴森科技',
 '誉衡药业',
 '江苏神通',
 '启明星辰',
 '闰土股份',
 '众业达',
 '龙星化工',
 '金洲管道',
 '巨星科技',
 '*ST中南',
 '盛路通信',
 '*ST晨鑫',
 '中原内配',
 '国星光电',
 '摩恩电气',
 '长高集团',
 '华软科技',
 '松芝股份',
 '百川股份',
 '欧菲光',
 '青龙管业',
 '益生股份',
 '晶澳科技',
 '赣锋锂业',
 '珠江啤酒',
 '嘉事堂',
 '沪电股份',
 '众应互联',
 '海格通信',
 '天齐锂业',
 '二六三',
 '申通快递',
 '三维工程',
 '*ST金正',
 '中超控股',
 '双环传动',
 'ST圣莱',
 '榕基软件',
 '立讯精密',
 '宝莫股份',
 '常宝股份',
 '富春环保',
 '新筑股份',
 '双塔食品',
 '广田集团',
 '润邦股份',
 '江海股份',
 '希努尔',
 '嘉麟杰',
 '大金重工',
 '金固股份',
 '浙江永强',
 '山东墨龙',
 '通鼎互联',
 '恒基达鑫',
 '荣盛石化',
 '华斯股份',
 '佳隆股份',
 '*ST辉丰',
 '雅化集团',
 '汉缆股份',
 '*ST科林',
 '山西证券',
 '*ST利源',
 '*ST鼎龙',
 '搜于特',
 '弘高创意',
 '鹏都农牧',
 '协鑫集成',
 '涪陵榨菜',
 '老板电器',
 '天汽模',
 '中顺洁柔',
 '达华智能',
 '*ST蓝丰',
 '宝馨科技',
 '金字火腿',
 '旷达科技',
 '恺英网络',
 '科士达',
 '银河电子',
 '日发精机',
 '齐峰新材',
 '浙江众成',
 '天桥起重',
 '光正眼科',
 '山东矿机',
 '新时达',
 '英飞拓',
 '*ST海源',
 '金财互联',
 '天顺风能',
 '天山铝业',
 '金杯电工',
 '杭锅股份',
 '*ST林重',
 '飞龙股份',
 '海联金汇',
 '司尔特',
 '云图控股',
 '亚太科技',
 '鸿路钢构',
 '中化岩土',
 '万和电气',
 '杰赛科技',
 '东方铁塔',
 '新联电子',
 '春兴精工',
 '金新农',
 '凯美特气',
 '千红制药',
 '尚荣医疗',
 '宝鼎科技',
 '南方轴承',
 '惠博普',
 '三七互娱',
 ...]

In [103]:
df = pro.hs_const(hs_type='SH') 
df.shape

(581, 5)

In [104]:
df = pro.hs_const(hs_type='SZ')
df.shape

(242, 5)

In [317]:
df = pro.daily(trade_date='20210409')
df.head()

,ts_code,trade_date,open,high,low,close,pre_close,change,pct_chg,vol,amount
0,000001.SZ,20210409,21.71,21.72,21.08,21.30,21.56,-0.26,-1.2059,398960.28,849870.878
1,000002.SZ,20210409,29.30,29.32,28.73,28.86,29.17,-0.31,-1.0627,528595.80,1527734.333
2,000004.SZ,20210409,17.38,17.56,17.21,17.40,17.32,0.08,0.4619,10182.01,17707.833
3,000005.SZ,20210409,2.34,2.34,2.27,2.28,2.32,-0.04,-1.7241,146370.58,33655.482
4,000006.SZ,20210409,5.33,5.36,5.26,5.32,5.33,-0.01,-0.1876,59751.84,31707.316

In [318]:
df1 = pd.concat([data,df],axis =1,keys =['ts_code','change'])
df1.head()

     ts_code                                                          \
     ts_code  symbol  name area industry market exchange list_status
0  000001.SZ  000001  平安银行   深圳       银行     主板     SZSE           L
1  000002.SZ  000002   万科A   深圳     全国地产     主板     SZSE           L
2  000004.SZ  000004  国华网安   深圳     软件服务     主板     SZSE           L
3  000005.SZ  000005  世纪星源   深圳     环境保护     主板     SZSE           L
4  000006.SZ  000006  深振业A   深圳     区域地产     主板     SZSE           L

                   ...     change                                        \
  list_date is_hs  ... trade_date   open   high    low  close pre_close
0  19910403     S  ...   20210409  21.71  21.72  21.08  21.30     21.56
1  19910129     S  ...   20210409  29.30  29.32  28.73  28.86     29.17
2  19910114     N  ...   20210409  17.38  17.56  17.21  17.40     17.32
3  19901210     N  ...   20210409   2.34   2.34   2.27   2.28      2.32
4  19920427     S  ...   20210409   5.33   5.36   5.26   5.32      5.33


  change pct_chg        vol       amount
0  -0.26 -1.2059  398960.28   849870.878
1  -0.31 -1.0627  528595.80  1527734.333
2   0.08  0.4619   10182.01    17707.833
3  -0.04 -1.7241  146370.58    33655.482
4  -0.01 -0.1876   59751.84    31707.316

[5 rows x 21 columns]

In [319]:
a = list(data.columns) +list(df.columns)

In [320]:
df1.columns = a

In [321]:
df1.head()

,ts_code,symbol,name,area,industry,market,exchange,list_status,list_date,is_hs,...,trade_date,open,high,low,close,pre_close,change,pct_chg,vol,amount
0,000001.SZ,000001,平安银行,深圳,银行,主板,SZSE,L,19910403,S,...,20210409,21.71,21.72,21.08,21.30,21.56,-0.26,-1.2059,398960.28,849870.878
1,000002.SZ,000002,万科A,深圳,全国地产,主板,SZSE,L,19910129,S,...,20210409,29.30,29.32,28.73,28.86,29.17,-0.31,-1.0627,528595.80,1527734.333
2,000004.SZ,000004,国华网安,深圳,软件服务,主板,SZSE,L,19910114,N,...,20210409,17.38,17.56,17.21,17.40,17.32,0.08,0.4619,10182.01,17707.833
3,000005.SZ,000005,世纪星源,深圳,环境保护,主板,SZSE,L,19901210,N,...,20210409,2.34,2.34,2.27,2.28,2.32,-0.04,-1.7241,146370.58,33655.482
4,000006.SZ,000006,深振业A,深圳,区域地产,主板,SZSE,L,19920427,S,...,20210409,5.33,5.36,5.26,5.32,5.33,-0.01,-0.1876,59751.84,31707.316

In [152]:
pro = ts.pro_api('6792f89c67a1f228aaf8aa19e6b0ca381504c16d8d5b7f75d76427a5')
df2 = pro.weekly(trade_date='20210407', fields='ts_code,trade_date,change,pre_close')

In [186]:
df2 = pro.weekly(trade_date='20210409', fields='ts_code,trade_date,change,pre_close')

In [ ]:
##df1没有加过去的成交记录，没有加股票本身的信息，接下来df1要加入当前日期之前的新闻讯息。

In [367]:
#df3 = pd.concat([df1,freq_words6],axis=1,join_axes = [df1.area])
df3 = pd.merge(df1,freq_words6,how='inner',left_on=df1['area'],right_on=freq_words6['area'])
df4 = df3.dropna(axis=0,subset = ["change"])

In [368]:
df4.head()

,key_0,ts_code,symbol,name,area_x,industry,market,exchange,list_status,list_date,...,high,low,close,pre_close,change,pct_chg,vol,amount,area_y,20210408
0,北京,000008.SZ,000008,神州高铁,北京,运输设备,主板,SZSE,L,19920507,...,2.33,2.30,2.32,2.33,-0.01,-0.4292,96501.65,22302.950,北京,3
1,北京,000046.SZ,000046,泛海控股,北京,多元金融,主板,SZSE,L,19940912,...,2.81,2.78,2.79,2.79,0.00,0.0000,82009.54,22885.973,北京,3
2,北京,000065.SZ,000065,北方国际,北京,建筑工程,主板,SZSE,L,19980605,...,9.54,9.21,9.25,9.73,-0.48,-4.9332,450846.86,421067.384,北京,3
3,北京,000151.SZ,000151,中成股份,北京,商贸代理,主板,SZSE,L,20000906,...,8.35,8.12,8.22,8.24,-0.02,-0.2427,155937.48,128025.675,北京,3
4,北京,000402.SZ,000402,金融街,北京,全国地产,主板,SZSE,L,19960626,...,6.90,6.70,6.75,6.73,0.02,0.2972,211834.88,143490.673,北京,3

In [356]:
from scipy.stats import pearsonr

In [369]:
na = df4[df4.change.isna()]
na.shape

(0, 24)

In [370]:
na

Empty DataFrame
Columns: [key_0, ts_code, symbol, name, area_x, industry, market, exchange, list_status, list_date, is_hs, ts_code, trade_date, open, high, low, close, pre_close, change, pct_chg, vol, amount, area_y, 20210408]
Index: []

[0 rows x 24 columns]

In [371]:
corr = pearsonr(df4['20210408'],df4['change'])

In [373]:
print(corr[0], corr[1])

-0.03206754564884792 0.12809489907211297